repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [--remove-unused-variables, --remove-duplicate-keys, --remove-all-unused-imports, --ignore-init-module-imports]

- repo: https://github.com/asottile/pyupgrade
  rev: v2.26.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/PyCQA/isort
  rev: 5.9.3
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
    language_version: python3
